# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-11 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='.', max_length=256),
            preserve_default=False,
        ),
    ]
