# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-03 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='GR'),
            preserve_default=False,
        ),
    ]
