# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-12 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='desc',
            new_name='text',
        ),
    ]
